dataformCoreVersion: 3.0.0-beta.4
defaultProject: core-361119
defaultLocation: us
defaultDataset: movielens
defaultAssertionDataset: movielens_assertions
vars:
    LOAD_GCS_BUCKET: landed_files/movielens
    RAW_DATA: movielens_staging
    TARGET_DATA: movielens
